### ISSUE TITLE
Does Palette work now?

### ISSUE THREAD

**Issue by TumVink** [cristianpjensen/thesis-pat-reconstruction#1]
Heyy Cristian,

Your project seems so interesting!
I am from the Palette repo, and am struggling still with the terrible performance of colourization task of Palette. And I saw your issue https://github.com/Janspiry/Palette-Image-to-Image-Diffusion-Models/issues/76

Does your model work out now? If so, could you share how did you solve this?

BW,
Jingsong

**Comment by cristianpjensen** [comment]
@TumVink Yes, I got it working! Since it was quite a long time ago, I do not remember exactly how I resolved the issue. You can take a look at [my implementation](https://github.com/cristianpjensen/thesis-pai-reconstruction/blob/master/models/palette.py).
