### ISSUE TITLE
 CUDA out of memory. What can I do?

### ISSUE THREAD

**Issue by PrinceYao1001** [cristianpjensen/thesis-pat-reconstruction#2]
When I traind with 256*256*1 image and hoped to realize conditional colorizaion，but always CUDA out of memory. What can I do with that? And can I use RGB image as condition? Looking forward to your reply, thanks~

**Comment by cristianpjensen** [comment]
CUDA out of memory is caused by your GPU not having enough memory to hold all the tensors. You could lower the batch size to prevent this.
